### ISSUE TITLE
Merge C# SDK into Unity SDK

### ISSUE THREAD

**Issue by bfops** [clockworklabs/com.clockworklabs.spacetimedbsdk-archive#53]

**Comment by cloutiertyler** [comment]
For context here, as Zeke and I were looking through the code of the CSharp SDK, we realized that it included references to Unity which were IF DEF'd out. The original idea was to have a pure CSharp SDK and a separate Unity SDK package which included or referenced the CSharp SDK, but what we have now is basically just two repos with the same code. Until and unless we find that we actually need a CSharp SDK, I would like to simplify by merging these two repositories and if necessary no longer publishing the CSharp SDK as a Nuget package. Right now it causes quite bit of confusion and upkeep to keep everything in sync.

If someone complains about the missing Nuget package, then we can reconsider publishing a CSharp SDK.

From a business standpoint, almost all of our users are going to be using SpacetimeDB from CSharp via Unity.

**Comment by RReverser** [comment]
Yeah the code is the same, just with ifdefs (I think always was?).

The Unity repo has a bunch of meta files that are only used by Unity and I think separate repos was a way to split those out, so one is just a Git repo for Unity package manager and another is the actual maintainable source.

Last time we talked with @jdetter about this stuff, he suggested we might just disable PRs on the Unity repo to make this clearer.

Note that Unity repo also needs to have some precompiled DLLs for dependencies - something that would certainly be inconvenient to hold in the _actual_ source code repo.

**Comment by bfops** [comment]
I don't personally see the "maintainable source" as separate from the rest of the Unity SDK, since the main output product is just the Unity SDK. We've also had several issues arise when we make changes to "only" the C# SDK without integrating + testing them in the Unity SDK, so imo it would be clearer and simpler for everyone to not have the illusion that they're separate repos and can really be meaningfully modified independently.

> Note that Unity repo also needs to have some precompiled DLLs for dependencies - something that would certainly be inconvenient to hold in the actual source code repo.

I think I'm missing something - why would this be more inconvenient to maintain in one repo vs the other?

**Comment by RReverser** [comment]
> We've also had several issues arise when we make changes to "only" the C# SDK without integrating + testing them in the Unity SDK

Yes, I had some ideas around automating it, but that's still different than just merging repos.

> I think I'm missing something - why would this be more inconvenient to maintain in one repo vs the other?

The thing is that those DLLs are not / should not be part of the source at all. In regular C# project they're just declared as csproj dependencies, and only for Unity they need to be pulled from NuGet and published as binary assets.

Basically, it's a red herring to think of Unity SDK repo as regular repo altogether; it only exists because Unity doesn't have proper package manager for 3rd-party authors and encourages them to point to Git instead. That is, it's just a store for built binary assets + couple of script files, rather than something that should be maintained by hand separately from C# source.

**Comment by bfops** [comment]
Closing in favor of https://github.com/clockworklabs/spacetimedb-csharp-sdk/issues/114
